// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HOPS.Migrations
{
    [DbContext(typeof(HOPSContext))]
    [Migration("20261007114737_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("HOPS.Models.BrewBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ActualABV")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ApparentAttenuation")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BottlingDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BottlingPlato")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BottlingTemperature")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BottlingVolume")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BrewDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrewNote")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BrewRecipeVersionId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BrewhouseEfficiency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FermentationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FermentationStartPlato")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MashWaterPercentage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RatingNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseIrishMoss")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseSilicaSol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseWhirlfloc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BrewRecipeVersionId");

                    b.ToTable("BrewBatch");
                });

            modelBuilder.Entity("HOPS.Models.BrewHop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AlphaAcid")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BrewBatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HopAdditionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BrewBatchId");

                    b.ToTable("BrewHop");
                });

            modelBuilder.Entity("HOPS.Models.BrewRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BrewRecipe");
                });

            modelBuilder.Entity("HOPS.Models.BrewRecipeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ApparantAttenuation")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bitterness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoilDuration")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BrewRecipeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BrewhouseEfficiency")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Carbonation")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Color")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedABV")
                        .HasColumnType("TEXT");

                    b.Property<int>("FermentationTemperature")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MashWaterPercentage")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaturationWeeksMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaturationWeeksMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OriginalGravity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalWater")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseIrishMoss")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseSilicaSol")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseWhirlfloc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BrewRecipeId");

                    b.ToTable("BrewRecipeVersion");
                });

            modelBuilder.Entity("HOPS.Models.FermentationAddition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BrewRecipeVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrewRecipeVersionId");

                    b.ToTable("FermentationAddition");
                });

            modelBuilder.Entity("HOPS.Models.HopAddition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AlphaAcid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BrewRecipeVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrewRecipeVersionId");

                    b.ToTable("HopAddition");
                });

            modelBuilder.Entity("HOPS.Models.MaltAddition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BrewRecipeVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrewRecipeVersionId");

                    b.ToTable("MaltAddition");
                });

            modelBuilder.Entity("HOPS.Models.MashStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BrewRecipeVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BrewRecipeVersionId");

                    b.ToTable("MashStep");
                });

            modelBuilder.Entity("HOPS.Models.WaterAddition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BrewBatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BrewRecipeVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrewBatchId");

                    b.HasIndex("BrewRecipeVersionId");

                    b.ToTable("WaterAddition");
                });

            modelBuilder.Entity("HOPS.Models.YeastAddition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BrewBatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BrewRecipeVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrewBatchId");

                    b.HasIndex("BrewRecipeVersionId");

                    b.ToTable("YeastAddition");
                });

            modelBuilder.Entity("HOPS.Models.BrewBatch", b =>
                {
                    b.HasOne("HOPS.Models.BrewRecipeVersion", "BrewRecipeVersion")
                        .WithMany()
                        .HasForeignKey("BrewRecipeVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrewRecipeVersion");
                });

            modelBuilder.Entity("HOPS.Models.BrewHop", b =>
                {
                    b.HasOne("HOPS.Models.BrewBatch", null)
                        .WithMany("Hops")
                        .HasForeignKey("BrewBatchId");
                });

            modelBuilder.Entity("HOPS.Models.BrewRecipeVersion", b =>
                {
                    b.HasOne("HOPS.Models.BrewRecipe", null)
                        .WithMany("Versions")
                        .HasForeignKey("BrewRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HOPS.Models.FermentationAddition", b =>
                {
                    b.HasOne("HOPS.Models.BrewRecipeVersion", null)
                        .WithMany("FermentationAdditions")
                        .HasForeignKey("BrewRecipeVersionId");
                });

            modelBuilder.Entity("HOPS.Models.HopAddition", b =>
                {
                    b.HasOne("HOPS.Models.BrewRecipeVersion", null)
                        .WithMany("HopAdditions")
                        .HasForeignKey("BrewRecipeVersionId");
                });

            modelBuilder.Entity("HOPS.Models.MaltAddition", b =>
                {
                    b.HasOne("HOPS.Models.BrewRecipeVersion", null)
                        .WithMany("MaltAdditions")
                        .HasForeignKey("BrewRecipeVersionId");
                });

            modelBuilder.Entity("HOPS.Models.MashStep", b =>
                {
                    b.HasOne("HOPS.Models.BrewRecipeVersion", null)
                        .WithMany("MashSteps")
                        .HasForeignKey("BrewRecipeVersionId");
                });

            modelBuilder.Entity("HOPS.Models.WaterAddition", b =>
                {
                    b.HasOne("HOPS.Models.BrewBatch", null)
                        .WithMany("WaterAdditions")
                        .HasForeignKey("BrewBatchId");

                    b.HasOne("HOPS.Models.BrewRecipeVersion", null)
                        .WithMany("WaterAdditions")
                        .HasForeignKey("BrewRecipeVersionId");
                });

            modelBuilder.Entity("HOPS.Models.YeastAddition", b =>
                {
                    b.HasOne("HOPS.Models.BrewBatch", null)
                        .WithMany("YeastAdditions")
                        .HasForeignKey("BrewBatchId");

                    b.HasOne("HOPS.Models.BrewRecipeVersion", null)
                        .WithMany("YeastAdditions")
                        .HasForeignKey("BrewRecipeVersionId");
                });

            modelBuilder.Entity("HOPS.Models.BrewBatch", b =>
                {
                    b.Navigation("Hops");

                    b.Navigation("WaterAdditions");

                    b.Navigation("YeastAdditions");
                });

            modelBuilder.Entity("HOPS.Models.BrewRecipe", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("HOPS.Models.BrewRecipeVersion", b =>
                {
                    b.Navigation("FermentationAdditions");

                    b.Navigation("HopAdditions");

                    b.Navigation("MaltAdditions");

                    b.Navigation("MashSteps");

                    b.Navigation("WaterAdditions");

                    b.Navigation("YeastAdditions");
                });
#pragma warning restore 612, 618
        }
    }
}
