//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOPS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HOPS.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ist.
        /// </summary>
        public static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkoholgehalt.
        /// </summary>
        public static string ActualABV {
            get {
                return ResourceManager.GetString("ActualABV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusatz.
        /// </summary>
        public static string Addition {
            get {
                return ResourceManager.GetString("Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        public static string AlphaAcid {
            get {
                return ResourceManager.GetString("AlphaAcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menge.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endvergärungsgrad.
        /// </summary>
        public static string ApparentAttenuation {
            get {
                return ResourceManager.GetString("ApparentAttenuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version gelöscht.
        /// </summary>
        public static string BAA {
            get {
                return ResourceManager.GetString("BAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grunddaten.
        /// </summary>
        public static string BaseData {
            get {
                return ResourceManager.GetString("BaseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sud.
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Sud wurde verworfen..
        /// </summary>
        public static string BatchIsDestroyed {
            get {
                return ResourceManager.GetString("BatchIsDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausbeute.
        /// </summary>
        public static string BatchSize {
            get {
                return ResourceManager.GetString("BatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bittere.
        /// </summary>
        public static string Bitterness {
            get {
                return ResourceManager.GetString("Bitterness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Würzekochen.
        /// </summary>
        public static string Boil {
            get {
                return ResourceManager.GetString("Boil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kochzeit.
        /// </summary>
        public static string BoilDuration {
            get {
                return ResourceManager.GetString("BoilDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flaschengröße.
        /// </summary>
        public static string BottleSize {
            get {
                return ResourceManager.GetString("BottleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abfülldatum.
        /// </summary>
        public static string BottlingDate {
            get {
                return ResourceManager.GetString("BottlingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stammwürze.
        /// </summary>
        public static string BottlingPlato {
            get {
                return ResourceManager.GetString("BottlingPlato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abfülltemperatur.
        /// </summary>
        public static string BottlingTemperature {
            get {
                return ResourceManager.GetString("BottlingTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abfüllvolumen.
        /// </summary>
        public static string BottlingVolume {
            get {
                return ResourceManager.GetString("BottlingVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brauen.
        /// </summary>
        public static string Brew {
            get {
                return ResourceManager.GetString("Brew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brautagebuch.
        /// </summary>
        public static string BrewBatchPages {
            get {
                return ResourceManager.GetString("BrewBatchPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braudatum.
        /// </summary>
        public static string BrewDate {
            get {
                return ResourceManager.GetString("BrewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA.
        /// </summary>
        public static string BrewhouseEfficiency {
            get {
                return ResourceManager.GetString("BrewhouseEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braudatum.
        /// </summary>
        public static string BrewingDate {
            get {
                return ResourceManager.GetString("BrewingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brauwasser.
        /// </summary>
        public static string BrewingWater {
            get {
                return ResourceManager.GetString("BrewingWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brautagebuch.
        /// </summary>
        public static string BrewLog {
            get {
                return ResourceManager.GetString("BrewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braubemerkungen.
        /// </summary>
        public static string BrewNote {
            get {
                return ResourceManager.GetString("BrewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezept.
        /// </summary>
        public static string BrewRecipes {
            get {
                return ResourceManager.GetString("BrewRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calciumchlorid (CaCl2).
        /// </summary>
        public static string CalciumChloride {
            get {
                return ResourceManager.GetString("CalciumChloride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calciumsulfat (CaSO4).
        /// </summary>
        public static string CalciumSulfate {
            get {
                return ResourceManager.GetString("CalciumSulfate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Cancle {
            get {
                return ResourceManager.GetString("Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karbonisierung.
        /// </summary>
        public static string Carbonation {
            get {
                return ResourceManager.GetString("Carbonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbe.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesen Sud wirklich löschen?.
        /// </summary>
        public static string ConfirmDeleteBatch {
            get {
                return ResourceManager.GetString("ConfirmDeleteBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Rezeptversion wirklich löschen.
        /// </summary>
        public static string ConfirmDeleteVersion {
            get {
                return ResourceManager.GetString("ConfirmDeleteVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anlegen.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Rezept.
        /// </summary>
        public static string CreateRecipe {
            get {
                return ResourceManager.GetString("CreateRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version löschen.
        /// </summary>
        public static string DeleteVersion {
            get {
                return ResourceManager.GetString("DeleteVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destilliertes Wasser.
        /// </summary>
        public static string DestilledWater {
            get {
                return ResourceManager.GetString("DestilledWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dauer.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sud bearbeiten.
        /// </summary>
        public static string EditBatch {
            get {
                return ResourceManager.GetString("EditBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezept bearbeiten.
        /// </summary>
        public static string EditRecipe {
            get {
                return ResourceManager.GetString("EditRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkohol.
        /// </summary>
        public static string EstimatedABV {
            get {
                return ResourceManager.GetString("EstimatedABV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gärzugabe.
        /// </summary>
        public static string FermentationAddition {
            get {
                return ResourceManager.GetString("FermentationAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gärzugaben.
        /// </summary>
        public static string FermentationAdditions {
            get {
                return ResourceManager.GetString("FermentationAdditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gärung und Reifung.
        /// </summary>
        public static string FermentationAndAging {
            get {
                return ResourceManager.GetString("FermentationAndAging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gärbeginn.
        /// </summary>
        public static string FermentationStartDate {
            get {
                return ResourceManager.GetString("FermentationStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stammwürze.
        /// </summary>
        public static string FermentationStartPlato {
            get {
                return ResourceManager.GetString("FermentationStartPlato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gärtemperatur.
        /// </summary>
        public static string FermentationTemperature {
            get {
                return ResourceManager.GetString("FermentationTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klärmittel.
        /// </summary>
        public static string FiningAgents {
            get {
                return ResourceManager.GetString("FiningAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schüttung.
        /// </summary>
        public static string GrainBill {
            get {
                return ResourceManager.GetString("GrainBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopfen.
        /// </summary>
        public static string Hop {
            get {
                return ResourceManager.GetString("Hop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopfengaben.
        /// </summary>
        public static string HopAdditions {
            get {
                return ResourceManager.GetString("HopAdditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopfen.
        /// </summary>
        public static string Hops {
            get {
                return ResourceManager.GetString("Hops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zutaten.
        /// </summary>
        public static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelöscht.
        /// </summary>
        public static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelöscht.
        /// </summary>
        public static string IsDestroyed {
            get {
                return ResourceManager.GetString("IsDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        public static string LabelCount {
            get {
                return ResourceManager.GetString("LabelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten.
        /// </summary>
        public static string LabelData {
            get {
                return ResourceManager.GetString("LabelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milchsäure.
        /// </summary>
        public static string LacticAcid {
            get {
                return ResourceManager.GetString("LacticAcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnesiumsulfat (MgSO4).
        /// </summary>
        public static string MagnesiumSulfate {
            get {
                return ResourceManager.GetString("MagnesiumSulfate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malz.
        /// </summary>
        public static string Malt {
            get {
                return ResourceManager.GetString("Malt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maischplan.
        /// </summary>
        public static string MashSchedule {
            get {
                return ResourceManager.GetString("MashSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptguss.
        /// </summary>
        public static string MashWater {
            get {
                return ResourceManager.GetString("MashWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptguss.
        /// </summary>
        public static string MashWaterPercentage {
            get {
                return ResourceManager.GetString("MashWaterPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reifezeit.
        /// </summary>
        public static string MaturationTime {
            get {
                return ResourceManager.GetString("MaturationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reifezeit bis.
        /// </summary>
        public static string MaturationWeeksMax {
            get {
                return ResourceManager.GetString("MaturationWeeksMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reifezeit von.
        /// </summary>
        public static string MaturationWeeksMin {
            get {
                return ResourceManager.GetString("MaturationWeeksMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reif.
        /// </summary>
        public static string Mature {
            get {
                return ResourceManager.GetString("Mature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschieben.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Sud.
        /// </summary>
        public static string NewBatch {
            get {
                return ResourceManager.GetString("NewBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Rezept.
        /// </summary>
        public static string NewRecipe {
            get {
                return ResourceManager.GetString("NewRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Gärzugaben.
        /// </summary>
        public static string NoFermentationAdditions {
            get {
                return ResourceManager.GetString("NoFermentationAdditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notizen.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht bewertet.
        /// </summary>
        public static string NotRated {
            get {
                return ResourceManager.GetString("NotRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stammwürze.
        /// </summary>
        public static string OriginalGravity {
            get {
                return ResourceManager.GetString("OriginalGravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Zutaten.
        /// </summary>
        public static string OtherIngredients {
            get {
                return ResourceManager.GetString("OtherIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorschau.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haushaltszucker.
        /// </summary>
        public static string PrimingSugar {
            get {
                return ResourceManager.GetString("PrimingSugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drucken.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Drucken.
        /// </summary>
        public static string PrintLabel {
            get {
                return ResourceManager.GetString("PrintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewertung.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bemerkung.
        /// </summary>
        public static string RatingNote {
            get {
                return ResourceManager.GetString("RatingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trinkreif.
        /// </summary>
        public static string ReadyToDrink {
            get {
                return ResourceManager.GetString("ReadyToDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezept.
        /// </summary>
        public static string Recipe {
            get {
                return ResourceManager.GetString("Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezept gelöscht.
        /// </summary>
        public static string RecipeDeleted {
            get {
                return ResourceManager.GetString("RecipeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest-Co2.
        /// </summary>
        public static string ResidualCo2 {
            get {
                return ResourceManager.GetString("ResidualCo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgewählt.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzeigen.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachguss.
        /// </summary>
        public static string SpargeWater {
            get {
                return ResourceManager.GetString("SpargeWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schritt.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bierstil.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _START_ bis _END_ von _TOTAL_ Suden.
        /// </summary>
        public static string Table_Info {
            get {
                return ResourceManager.GetString("Table_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Sude vorhanden.
        /// </summary>
        public static string Table_InfoEmpty {
            get {
                return ResourceManager.GetString("Table_InfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _MENU_ Einträge.
        /// </summary>
        public static string Table_LengthMenu {
            get {
                return ResourceManager.GetString("Table_LengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezept oder Stil.
        /// </summary>
        public static string Table_Placeholder {
            get {
                return ResourceManager.GetString("Table_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine passenden Sude gefunden.
        /// </summary>
        public static string Table_ZeroRecords {
            get {
                return ResourceManager.GetString("Table_ZeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll / Ist.
        /// </summary>
        public static string TargetActual {
            get {
                return ResourceManager.GetString("TargetActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatur.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeit.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zur Liste.
        /// </summary>
        public static string ToList {
            get {
                return ResourceManager.GetString("ToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasser Gesamt.
        /// </summary>
        public static string TotalWater {
            get {
                return ResourceManager.GetString("TotalWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einheit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irish Moss.
        /// </summary>
        public static string UseIrishMoss {
            get {
                return ResourceManager.GetString("UseIrishMoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kieselsol.
        /// </summary>
        public static string UseSilicaSol {
            get {
                return ResourceManager.GetString("UseSilicaSol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whirlfloc.
        /// </summary>
        public static string UseWhirlfloc {
            get {
                return ResourceManager.GetString("UseWhirlfloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version gelöscht.
        /// </summary>
        public static string VersionDeleted {
            get {
                return ResourceManager.GetString("VersionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzeigen.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasserzusatz.
        /// </summary>
        public static string WaterAddition {
            get {
                return ResourceManager.GetString("WaterAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wasser Zusätze.
        /// </summary>
        public static string WaterAdditions {
            get {
                return ResourceManager.GetString("WaterAdditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wochen.
        /// </summary>
        public static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hefe.
        /// </summary>
        public static string Yeast {
            get {
                return ResourceManager.GetString("Yeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hefen.
        /// </summary>
        public static string Yeasts {
            get {
                return ResourceManager.GetString("Yeasts", resourceCulture);
            }
        }
    }
}
